# Sections for "Generate release notes", by pull request label.
changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: DDEV compatibility
      labels:
        - ddev-compat
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
        - dependencies
    - title: Other changes
      labels:
        - "*"
