#!/usr/bin/env bash
#ddev-generated
# Shared functions for the fire-worktree-* host commands. Sourced, never run.
# Keep this file compatible with Bash 3.2, the macOS default, and avoid jq, yq
# and Python so the commands work on any machine that runs DDEV.

FW_CONFIG_NAME=config.worktree.local.yaml
FW_MARKER='# Generated by ddev fire-worktree-start. Rerun that command instead of editing.'
FW_SEED_PREFIX=fire-worktree-seed
FW_LOCK="${TMPDIR:-/tmp}"
FW_LOCK="${FW_LOCK%/}/ddev-fire-worktrees.lock"

fw::die() {
  printf '%s\n' "$*" >&2
  exit 1
}

fw::warn() {
  printf 'Warning: %s\n' "$*" >&2
}

# fw::is_legacy_marker LINE: true for the first line of a config file written by
# the project-local worktree commands this add-on replaces.
fw::is_legacy_marker() {
  case $1 in
    '# Generated by ddev worktree-start.' | '# Generated by ddev worktree-prepare.' | '# Generated by devops/scripts/worktree-setup.')
      return 0
      ;;
  esac
  return 1
}

# fw::first_line FILE
fw::first_line() {
  local line=
  IFS= read -r line <"$1" || true
  printf '%s' "$line"
}

# fw::is_generated FILE: true when this add-on or a command it replaces wrote FILE.
fw::is_generated() {
  local first
  [[ -f "$1" && ! -L "$1" ]] || return 1
  first=$(fw::first_line "$1")
  [[ "$first" == "$FW_MARKER" ]] || fw::is_legacy_marker "$first"
}

# fw::context DIR: describe the Git checkout that contains DIR. Sets FW_ROOT,
# FW_GIT_DIR, FW_COMMON_DIR, FW_PRIMARY_ROOT (empty for a bare repository) and
# FW_IS_PRIMARY.
fw::context() {
  local top
  top=$(cd "$1" && git rev-parse --show-toplevel 2>/dev/null) || fw::die "$1 is not inside a Git checkout."
  FW_ROOT=$(cd "$top" && pwd -P)
  FW_GIT_DIR=$(cd "$FW_ROOT" && cd "$(git rev-parse --git-dir)" && pwd -P)
  FW_COMMON_DIR=$(cd "$FW_ROOT" && cd "$(git rev-parse --git-common-dir)" && pwd -P)
  FW_PRIMARY_ROOT=
  if [[ "$(basename "$FW_COMMON_DIR")" == .git ]]; then
    FW_PRIMARY_ROOT=$(dirname "$FW_COMMON_DIR")
  fi
  FW_IS_PRIMARY=false
  if [[ "$FW_GIT_DIR" == "$FW_COMMON_DIR" ]]; then
    FW_IS_PRIMARY=true
  fi
  [[ -f "$FW_ROOT/.ddev/config.yaml" ]] || fw::die "$FW_ROOT has no .ddev/config.yaml."
}

# YAML readers. They understand the subset DDEV writes: top-level scalars, one
# level of nesting, and block (- item) or flow ([a, b]) lists.
FW_AWK_CLEAN='
  function clean(s) {
    sub(/[ \t]+#.*$/, "", s)
    gsub(/^[ \t]+|[ \t]+$/, "", s)
    if (s ~ /^".*"$/ || s ~ /^\047.*\047$/) s = substr(s, 2, length(s) - 2)
    return s
  }'

# fw::yaml_scalar FILE KEY
fw::yaml_scalar() {
  awk -v key="$2" "$FW_AWK_CLEAN"'
    index($0, key ":") == 1 {
      rest = substr($0, length(key) + 2)
      if (rest == "" || rest ~ /^[ \t]/) { print clean(rest); exit }
    }' "$1"
}

# fw::yaml_nested FILE PARENT KEY
fw::yaml_nested() {
  awk -v parent="$2" -v key="$3" "$FW_AWK_CLEAN"'
    index($0, parent ":") == 1 { inblock = 1; next }
    inblock && /^[^ \t#]/ { exit }
    inblock {
      line = $0
      sub(/^[ \t]+/, "", line)
      if (index(line, key ":") == 1) {
        rest = substr(line, length(key) + 2)
        if (rest == "" || rest ~ /^[ \t]/) { print clean(rest); exit }
      }
    }' "$1"
}

# fw::yaml_list FILE KEY: print each item of a top-level list on its own line.
fw::yaml_list() {
  awk -v key="$2" "$FW_AWK_CLEAN"'
    !inlist && index($0, key ":") == 1 {
      rest = substr($0, length(key) + 2)
      if (rest != "" && rest !~ /^[ \t]/) next
      sub(/^[ \t]+/, "", rest)
      sub(/[ \t]+#.*$/, "", rest)
      if (rest ~ /^\[/) {
        sub(/^\[/, "", rest)
        sub(/\][ \t]*$/, "", rest)
        n = split(rest, items, ",")
        for (i = 1; i <= n; i++) { v = clean(items[i]); if (v != "") print v }
        exit
      }
      inlist = 1
      next
    }
    inlist && /^[ \t]*-([ \t]|$)/ {
      v = $0
      sub(/^[ \t]*-[ \t]*/, "", v)
      v = clean(v)
      if (v != "") print v
      next
    }
    inlist && /^[ \t]*(#.*)?$/ { next }
    inlist { exit }' "$1"
}

# fw::config_files DIR: DIR's DDEV config files in DDEV's load order, without
# the files worktree commands generate.
fw::config_files() {
  local f
  printf '%s\n' "$1/.ddev/config.yaml"
  (
    # DDEV loads config.*.y*ml in Go's byte order, which C-locale globbing matches.
    LC_ALL=C
    for f in "$1"/.ddev/config.*.y*ml; do
      [[ -f "$f" ]] || continue
      fw::is_generated "$f" && continue
      printf '%s\n' "$f"
    done
  )
}

# fw::config_scalar DIR KEY: the last value any config file sets.
fw::config_scalar() {
  local f v value=
  while IFS= read -r f; do
    v=$(fw::yaml_scalar "$f" "$2")
    if [[ -n "$v" ]]; then
      value=$v
    fi
  done < <(fw::config_files "$1")
  printf '%s' "$value"
}

# fw::config_nested DIR PARENT KEY
fw::config_nested() {
  local f v value=
  while IFS= read -r f; do
    v=$(fw::yaml_nested "$f" "$2" "$3")
    if [[ -n "$v" ]]; then
      value=$v
    fi
  done < <(fw::config_files "$1")
  printf '%s' "$value"
}

# fw::config_list DIR KEY: every config file's items, in load order.
fw::config_list() {
  local f
  while IFS= read -r f; do
    fw::yaml_list "$f" "$2"
  done < <(fw::config_files "$1")
}

# fw::setting DIR NAME DEFAULT: NAME from web_environment, where a later file
# (such as config.local.yaml) overrides an earlier one. Empty means DEFAULT.
fw::setting() {
  local item value=$3
  while IFS= read -r item; do
    if [[ "$item" == "$2="* && -n "${item#"$2="}" ]]; then
      value=${item#"$2="}
    fi
  done < <(fw::config_list "$1" web_environment)
  printf '%s' "$value"
}

# fw::slug TEXT MAX: lowercase letters, digits and single hyphens, at most MAX long.
fw::slug() {
  local s
  s=$(printf '%s' "$1" | LC_ALL=C tr '[:upper:]' '[:lower:]' | LC_ALL=C sed -e 's/[^a-z0-9]/-/g' -e 's/--*/-/g' -e 's/^-//' | cut -c "1-$2")
  printf '%s' "${s%-}"
}

# fw::project_name_of DIR: the DDEV name DIR's own config gives it. DDEV falls
# back to the directory name when config.yaml has no name.
fw::project_name_of() {
  local name
  name=$(fw::config_scalar "$1" name)
  if [[ -z "$name" ]]; then
    name=$(fw::slug "$(basename "$1")" 63)
  fi
  printf '%s' "$name"
}

# fw::primary_name: the primary checkout's DDEV project name. A config.yaml
# without name: gives each checkout a different name, so ask the primary's.
fw::primary_name() {
  local root=${FW_PRIMARY_ROOT:-$FW_ROOT}
  [[ -f "$root/.ddev/config.yaml" ]] || root=$FW_ROOT
  fw::project_name_of "$root"
}

# fw::generated_name DIR: the project name in DIR's generated config, if any.
fw::generated_name() {
  local f
  for f in "$1/.ddev/$FW_CONFIG_NAME" "$1/.ddev/config.worktree.yaml"; do
    if fw::is_generated "$f"; then
      fw::yaml_scalar "$f" name
      return 0
    fi
  done
  return 0
}

# fw::tld DIR
fw::tld() {
  local tld
  tld=$(fw::config_scalar "$1" project_tld)
  printf '%s' "${tld:-ddev.site}"
}

# fw::check_hostname HOST: DNS labels can't exceed 63 characters.
fw::check_hostname() {
  local rest=$1 label
  while [[ -n "$rest" ]]; do
    label=${rest%%.*}
    if [[ ${#label} -gt 63 ]]; then
      fw::die "Hostname $1 has a label longer than 63 characters. Shorten WORKTREE_NAME_PREFIX or the directory name."
    fi
    if [[ "$rest" == *.* ]]; then
      rest=${rest#*.}
    else
      rest=
    fi
  done
}

# fw::rewrite_hostnames DIR PRIMARY NAME: DIR's additional_hostnames for project
# NAME. <sub>.PRIMARY becomes <sub>.NAME; any other host becomes <host>.NAME.
fw::rewrite_hostnames() {
  local host new
  while IFS= read -r host; do
    [[ -n "$host" && "$host" != "$2" ]] || continue
    if [[ "$host" == *".$2" ]]; then
      new="${host%".$2"}.$3"
    else
      new="$host.$3"
    fi
    fw::check_hostname "$new"
    printf '%s\n' "$new"
  done < <(fw::config_list "$1" additional_hostnames)
}

# fw::db_volume_exists NAME: true once DDEV has created NAME's database volume.
fw::db_volume_exists() {
  docker volume ls -q 2>/dev/null | grep -Eq "^$1-(mariadb|mysql|postgres)\$"
}

fw::lock() {
  local waited=0 pid
  while ! mkdir "$FW_LOCK" 2>/dev/null; do
    pid=$(cat "$FW_LOCK/pid" 2>/dev/null || true)
    if [[ -n "$pid" ]] && ! kill -0 "$pid" 2>/dev/null; then
      rm -rf "$FW_LOCK"
      continue
    fi
    if ((waited % 30 == 0)); then
      echo 'Waiting for another worktree to finish starting...'
    fi
    if ((waited >= 1800)); then
      fw::die "Timed out waiting for $FW_LOCK. Delete it if no other worktree is starting."
    fi
    sleep 2
    waited=$((waited + 2))
  done
  echo $$ >"$FW_LOCK/pid"
  trap 'rm -rf "$FW_LOCK"' EXIT
}

fw::unlock() {
  rm -rf "$FW_LOCK"
  trap - EXIT
}

# Registry of worktrees this repository started, kept in the shared .git
# directory so it outlives removed checkouts. One "<name><TAB><path>" per line.
fw::registry_file() {
  printf '%s/fire-worktrees' "$FW_COMMON_DIR"
}

fw::registry_remove() {
  local file tmp
  file=$(fw::registry_file)
  [[ -f "$file" ]] || return 0
  tmp="$file.$$"
  awk -F '\t' -v name="$1" '$1 != name' "$file" >"$tmp" && mv "$tmp" "$file"
}

fw::registry_add() {
  fw::registry_remove "$1"
  printf '%s\t%s\n' "$1" "$2" >>"$(fw::registry_file)"
}

# fw::default_ref: the remote's default branch, as a local branch when one exists.
fw::default_ref() {
  local ref
  ref=$(git -C "$FW_ROOT" symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || true)
  ref=${ref#origin/}
  ref=${ref:-main}
  if ! git -C "$FW_ROOT" show-ref --verify --quiet "refs/heads/$ref" &&
    git -C "$FW_ROOT" show-ref --verify --quiet "refs/remotes/origin/$ref"; then
    ref="origin/$ref"
  fi
  printf '%s' "$ref"
}

# fw::seed_snapshot MODE: print the snapshot file to seed a new database from,
# or nothing for a fresh database.
fw::seed_snapshot() {
  local mode=$1 dir primary snap f newest='' type version
  case $mode in
    fresh)
      return 0
      ;;
    primary | latest)
      [[ -n "$FW_PRIMARY_ROOT" && -f "$FW_PRIMARY_ROOT/.ddev/config.yaml" ]] ||
        fw::die "No primary checkout with a DDEV project to copy the database from. Use --db=fresh."
      dir="$FW_PRIMARY_ROOT/.ddev/db_snapshots"
      if [[ "$mode" == primary ]]; then
        primary=$(fw::primary_name)
        snap="$FW_SEED_PREFIX-$(date +%Y%m%d%H%M%S)"
        echo "Snapshotting the $primary database to copy it into this worktree..." >&2
        if ddev snapshot "$primary" --name="$snap" >&2; then
          for f in "$dir/$snap"-*; do
            [[ -f "$f" ]] && newest=$f
          done
          # Keep only the newest seed snapshot.
          for f in "$dir/$FW_SEED_PREFIX"-*; do
            if [[ -f "$f" && "$f" != "$newest" ]]; then
              rm -f "$f"
            fi
          done
        else
          fw::warn "Couldn't snapshot $primary. Start it with 'ddev start' in $FW_PRIMARY_ROOT to copy its current data."
        fi
      fi
      if [[ -z "$newest" ]]; then
        # The newest snapshot that matches this worktree's database server.
        type=$(fw::config_nested "$FW_ROOT" database type)
        version=$(fw::config_nested "$FW_ROOT" database version)
        while IFS= read -r f; do
          [[ -f "$dir/$f" ]] || continue
          if [[ -n "$type" && -n "$version" && "$f" != *"-${type}_${version}."* ]]; then
            continue
          fi
          newest="$dir/$f"
          break
        done < <(ls -t "$dir" 2>/dev/null)
        if [[ -z "$newest" ]]; then
          fw::die "The primary checkout has no database snapshot to copy. Start its project, or use --db=fresh."
        fi
        if [[ "$mode" == primary ]]; then
          fw::warn "Using the older snapshot $(basename "$newest") instead."
        fi
      fi
      printf '%s' "$newest"
      ;;
    *)
      [[ -f "$mode" ]] || fw::die "--db must be primary, latest, fresh, a snapshot or a SQL dump; got $mode."
      printf '%s/%s' "$(cd "$(dirname "$mode")" && pwd -P)" "$(basename "$mode")"
      ;;
  esac
}

# fw::db_arg VALUE: a --db value with any file path made absolute, so it still
# points at the same file after the commands change directory.
fw::db_arg() {
  case $1 in
    '' | primary | latest | fresh) printf '%s' "$1" ;;
    *)
      [[ -f "$1" ]] || fw::die "--db must be primary, latest, fresh, a snapshot or a SQL dump; got $1."
      printf '%s/%s' "$(cd "$(dirname "$1")" && pwd -P)" "$(basename "$1")"
      ;;
  esac
}

# fw::is_dump FILE: true for a file ddev import-db reads, such as FIRE's
# reference/site-db.sql.gz, rather than a ddev snapshot.
fw::is_dump() {
  case $1 in
    *.sql | *.sql.gz | *.sql.bz2 | *.sql.xz | *.mysql | *.mysql.gz | *.zip | *.tgz | *.tar.gz) return 0 ;;
  esac
  return 1
}

# fw::build_command DIR: the command that finishes a worktree after its database
# is copied in, or "none".
fw::build_command() {
  local cmd
  cmd=$(fw::setting "$1" WORKTREE_BUILD_COMMAND "")
  if [[ -z "$cmd" ]]; then
    if [[ -f "$1/.ddev/commands/host/fire-build" ]]; then
      cmd='ddev fire-build --no-db-import'
    else
      case $(fw::config_scalar "$1" type) in
        # drush deploy needs Drupal 8.8 or later.
        drupal6 | drupal7) cmd='ddev drush updb -y' ;;
        drupal*) cmd='ddev drush deploy -y' ;;
        *) cmd=none ;;
      esac
    fi
  fi
  printf '%s' "$cmd"
}

# fw::populate_hint DIR: how to fill an empty database.
fw::populate_hint() {
  if [[ -f "$1/.ddev/commands/host/fire-build" ]]; then
    echo 'ddev fire-build'
  elif [[ -f "$1/fire.yml" ]]; then
    echo 'fire build'
  else
    echo 'ddev import-db --file=<dump>, or ddev pull <provider>'
  fi
}

# fw::copy_files SOURCE: copy gitignored local files that FW_ROOT lacks.
fw::copy_files() {
  local docroot list rel
  local -a files
  [[ -d "$1" && "$1" != "$FW_ROOT" ]] || return 0
  docroot=$(fw::config_scalar "$FW_ROOT" docroot)
  list=$(fw::setting "$FW_ROOT" WORKTREE_COPY_FILES ".ddev/config.local.yaml ${docroot:+$docroot/}sites/default/settings.local.php")
  read -r -a files <<<"$list"
  for rel in ${files[@]+"${files[@]}"}; do
    case $rel in
      /* | *..*)
        fw::warn "Skipping $rel in WORKTREE_COPY_FILES; use a path inside the project."
        continue
        ;;
    esac
    if [[ -f "$1/$rel" && ! -e "$FW_ROOT/$rel" && ! -L "$FW_ROOT/$rel" ]]; then
      mkdir -p "$(dirname "$FW_ROOT/$rel")"
      cp "$1/$rel" "$FW_ROOT/$rel"
      printf 'Copied %s\n' "$rel"
    fi
  done
}

# fw::write_config PRIMARY: write FW_ROOT's generated DDEV config for FW_NAME.
fw::write_config() {
  local cfg="$FW_ROOT/.ddev/$FW_CONFIG_NAME" hosts key fqdns
  hosts=$(fw::rewrite_hostnames "$FW_ROOT" "$1" "$FW_NAME") || exit 1
  fqdns=$(fw::config_list "$FW_ROOT" additional_fqdns | tr '\n' ' ')
  {
    printf '%s\n' "$FW_MARKER"
    # Replace rather than merge these keys, so this project never claims the
    # primary checkout's hostnames or host ports.
    printf 'override_config: true\nname: %s\n' "$FW_NAME"
    if [[ -n "$hosts" ]]; then
      printf 'additional_hostnames:\n'
      printf '%s\n' "$hosts" | sed 's/^/  - /'
    else
      printf 'additional_hostnames: []\n'
    fi
    printf 'additional_fqdns: []\n'
    for key in host_https_port host_webserver_port host_db_port host_mailpit_port host_xhgui_port; do
      if [[ -n "$(fw::config_scalar "$FW_ROOT" "$key")" ]]; then
        printf '%s: ""\n' "$key"
      fi
    done
  } >"$cfg.tmp"
  mv "$cfg.tmp" "$cfg"
  if [[ -n "${fqdns// /}" ]]; then
    echo "Left out additional_fqdns (${fqdns% }); two running projects can't share them."
  fi
}

# fw::start_worktree DIR DB BUILD: configure, start and build the linked worktree
# that contains DIR. DB is primary, latest, fresh or a snapshot file; empty means
# the WORKTREE_DB setting. BUILD is true or false.
fw::start_worktree() {
  local db=$2 build=$3 primary cfg legacy source prefix dir slug suffix f seed='' dump='' tld host cmd nested=false composer_root new_db=false
  fw::context "$1"
  if [[ "$FW_IS_PRIMARY" == true ]]; then
    fw::die 'Run fire-worktree-start in a linked Git worktree, not the primary checkout.'
  fi
  cd "$FW_ROOT" || exit 1
  cfg=".ddev/$FW_CONFIG_NAME"
  legacy=.ddev/config.worktree.yaml
  if [[ (-e "$cfg" || -L "$cfg") ]] && ! fw::is_generated "$cfg"; then
    fw::die "Refusing to overwrite $cfg; this add-on didn't write it."
  fi
  if [[ -e "$legacy" ]] && ! fw::is_generated "$legacy" && [[ -n "$(fw::yaml_scalar "$legacy" name)" ]]; then
    fw::die "$legacy sets name: and loads after $cfg. Remove it or its name: line."
  fi
  (
    LC_ALL=C
    for f in .ddev/config.*.y*ml; do
      [[ -f "$f" && "$(basename "$f")" > "$FW_CONFIG_NAME" ]] || continue
      fw::is_generated "$f" && continue
      if [[ -n "$(fw::yaml_scalar "$f" name)" ]]; then
        fw::die "$f sets name: and loads after $cfg, so it would override this worktree's project name."
      fi
    done
  ) || exit 1

  # Reuse the name of an existing environment, including ones the replaced
  # project-local commands created, so the worktree keeps its database.
  FW_NAME=$(fw::generated_name "$FW_ROOT")
  primary=$(fw::primary_name)
  if [[ -z "$FW_NAME" ]]; then
    # Path-based names stay stable across branch renames and tell apart
    # worktrees whose directory names match.
    prefix=$(fw::slug "$(fw::setting "$FW_ROOT" WORKTREE_NAME_PREFIX "$primary")" 12)
    dir=$(basename "$FW_ROOT")
    if [[ -n "$FW_PRIMARY_ROOT" ]]; then
      dir=${dir#"$(basename "$FW_PRIMARY_ROOT")-"}
    fi
    slug=$(fw::slug "$dir" 24)
    suffix=$(printf '%s' "$FW_ROOT" | cksum | awk '{print $1}')
    FW_NAME="${prefix:-wt}-${slug:-wt}-$suffix"
  fi
  if [[ "$FW_NAME" == "$primary" ]]; then
    fw::die "Refusing to give this worktree the primary project's name, $primary."
  fi
  fw::write_config "$primary"
  if fw::is_generated "$legacy"; then
    rm -f "$legacy"
  fi
  # DDEV gitignores config.*.local.yaml once it writes .ddev/.gitignore. Exclude
  # the file in Git too, so a checkout that never started stays clean.
  mkdir -p "$FW_COMMON_DIR/info"
  if ! grep -qxF "/.ddev/$FW_CONFIG_NAME" "$FW_COMMON_DIR/info/exclude" 2>/dev/null; then
    printf '/.ddev/%s\n' "$FW_CONFIG_NAME" >>"$FW_COMMON_DIR/info/exclude"
  fi
  fw::registry_add "$FW_NAME" "$FW_ROOT"

  # Creation names its source checkout. Otherwise use T3's hint, then the primary.
  source=${WORKTREE_SOURCE_ROOT:-${T3CODE_PROJECT_ROOT:-$FW_PRIMARY_ROOT}}
  fw::copy_files "$source"
  printf 'Configured DDEV project %s\n' "$FW_NAME"

  if [[ -n "$FW_PRIMARY_ROOT" && "$FW_ROOT" == "$FW_PRIMARY_ROOT"/* ]]; then
    nested=true
    fw::warn "This worktree is inside the primary checkout. If the primary project uses Mutagen, it syncs this whole worktree into its own container."
  fi

  db=${db:-$(fw::setting "$FW_ROOT" WORKTREE_DB primary)}
  fw::lock
  if ! fw::db_volume_exists "$FW_NAME"; then
    new_db=true
    seed=$(fw::seed_snapshot "$db")
  fi
  # DDEV seeds only from snapshots; a SQL dump is imported once it's running.
  if [[ -n "$seed" ]] && fw::is_dump "$seed"; then
    dump=$seed
    seed=
  fi
  if [[ -n "$seed" ]]; then
    printf 'Seeding the new database from %s\n' "$seed"
  fi
  if [[ "$nested" == true ]]; then
    # DDEV asks whether to use an unregistered nested project, defaulting to the
    # project around it. Answer yes; starting registers it for later commands.
    DDEV_NONINTERACTIVE=false ddev start ${seed:+"--seed-snapshot=$seed"} <<<y || fw::die 'ddev start failed.'
  else
    ddev start ${seed:+"--seed-snapshot=$seed"} || fw::die 'ddev start failed.'
  fi
  fw::unlock

  if [[ -n "$dump" ]]; then
    printf 'Importing %s into the new database\n' "$dump"
    ddev import-db --file="$dump" ||
      fw::die "The worktree is running, but the import failed. Fix the error, then run: ddev import-db --file=$dump"
  fi

  composer_root=$(fw::config_scalar "$FW_ROOT" composer_root)
  if [[ -f "${composer_root:-.}/composer.json" ]]; then
    ddev composer install || fw::die 'ddev composer install failed.'
  fi

  tld=$(fw::tld "$FW_ROOT")
  if [[ -n "$seed" || -n "$dump" ]]; then
    cmd=$(fw::build_command "$FW_ROOT")
    if [[ "$build" == true && "$cmd" != none ]]; then
      printf '\nBuilding with: %s\n' "$cmd"
      if ! bash -c "$cmd"; then
        fw::die "The worktree is running, but the build failed. Fix the error, then run: $cmd"
      fi
    elif [[ "$cmd" != none ]]; then
      printf '\nSkipped the build. To run it: %s\n' "$cmd"
    fi
    if [[ -f fire.yml && "$cmd" == 'ddev drush '* && -z "$(fw::setting "$FW_ROOT" WORKTREE_BUILD_COMMAND "")" ]]; then
      printf "This project uses FIRE, and drush deploy doesn't build its theme. To build everything\n"
      printf 'after each copy, set WORKTREE_BUILD_COMMAND=fire build --no-db-import (see the add-on README).\n'
    fi
  fi

  printf '\nWorktree URLs:\n  https://%s.%s\n' "$FW_NAME" "$tld"
  while IFS= read -r host; do
    [[ -n "$host" ]] && printf '  https://%s.%s\n' "$host" "$tld"
  done < <(fw::yaml_list "$cfg" additional_hostnames)
  if [[ "$new_db" == true && -z "$seed" && -z "$dump" ]]; then
    printf 'To populate the database: %s\n' "$(fw::populate_hint "$FW_ROOT")"
  fi
}
